### ISSUE TITLE
运行失败

### ISSUE THREAD

**Issue by lbzlb** [Jarvlis/bookSystem-frontend#1]
之前我使用20版本，然后用ai研究了一下，改成node16版本。还是不行
![image](https://github.com/Jarvlis/bookSystem-frontend/assets/105098674/2d59f29d-e74a-490f-86ba-c33faa8f4982)
ai回复如下：
这个警告信息表明在尝试从 antd 包中导入 ColorPicker 组件时出现了问题。antd 是 Ant Design 的 React 组件库，它可能提供了 ColorPicker 组件，但是您的项目中使用的 antd 版本可能不包含这个组件。

hode20版本错误如下:
`D:\WorkSpace\books\bookSystem-frontend-main>npm start

> ant-design-pro@5.2.0 start
> cross-env UMI_ENV=dev umi dev

Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
Bundle with webpack 5...
⏱️  MFSU Enabled
🚀 Starting Umi UI using umi@3.5.41...
🌈 Umi UI mini Ready on port 3000.
Starting the development server...

* Webpack █████████████████████████ building (10%) 0/2 entries 1/2 dependencies 0/1 modules 1 active
 node_modules\@umijs\preset-built-in\bundled\@pmmmwh\react-refresh-webpack-plugin\client\ReactRefreshEntry.js

node:internal/crypto/hash:79
  this[kHandle] = new _Hash(algorithm, xofLen, algorithmId, getHashCache());
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:79:19)
    at Object.createHash (node:crypto:139:10)
    at BulkUpdateDecorator.hashFactory (D:\WorkSpace\books\bookSystem-frontend-main\node_modules\@umijs\deps\compiled\webpack\5\bundle5.js:184161:18)
    at BulkUpdateDecorator.update (D:\WorkSpace\books\bookSystem-frontend-main\node_modules\@umijs\deps\compiled\webpack\5\bundle5.js:184062:50)
    at OriginalSource.updateHash (D:\WorkSpace\books\bookSystem-frontend-main\node_modules\@umijs\deps\compiled\webpack-sources2\index.js:1:51038)
    at NormalModule._initBuildHash (D:\WorkSpace\books\bookSystem-frontend-main\node_modules\@umijs\deps\compiled\webpack\5\bundle5.js:115961:17)
    at handleParseResult (D:\WorkSpace\books\bookSystem-frontend-main\node_modules\@umijs\deps\compiled\webpack\5\bundle5.js:116027:10)
    at D:\WorkSpace\books\bookSystem-frontend-main\node_modules\@umijs\deps\compiled\webpack\5\bundle5.js:116119:4
    at processResult (D:\WorkSpace\books\bookSystem-frontend-main\node_modules\@umijs\deps\compiled\webpack\5\bundle5.js:115836:11)
    at D:\WorkSpace\books\bookSystem-frontend-main\node_modules\@umijs\deps\compiled\webpack\5\bundle5.js:115900:5
    at D:\WorkSpace\books\bookSystem-frontend-main\node_modules\@umijs\deps\compiled\webpack\5\bundle5.js:35132:3
    at iterateNormalLoaders (D:\WorkSpace\books\bookSystem-frontend-main\node_modules\@umijs\deps\compiled\webpack\5\bundle5.js:34958:10)
    at Array.<anonymous> (D:\WorkSpace\books\bookSystem-frontend-main\node_modules\@umijs\deps\compiled\webpack\5\bundle5.js:34949:4)
    at runCallbacks (D:\WorkSpace\books\bookSystem-frontend-main\node_modules\@umijs\deps\compiled\webpack\5\bundle5.js:24341:15)
    at D:\WorkSpace\books\bookSystem-frontend-main\node_modules\@umijs\deps\compiled\webpack\5\bundle5.js:24514:4
    at D:\WorkSpace\books\bookSystem-frontend-main\node_modules\@umijs\deps\compiled\webpack\5\bundle5.js:33829:16 {
  opensslErrorStack: [
    'error:03000086:digital envelope routines::initialization error',
    'error:0308010C:digital envelope routines::unsupported'
  ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v20.15.0`
ai回复如下：
这个错误信息表明在使用 Webpack 5 进行打包时，遇到了一个与 OpenSSL 相关的错误。这个错误通常是由于您的 Node.js 版本（在这个案例中是 v20.15.0）不支持某些 OpenSSL 功能导致的。

错误信息中提到的 error:0308010C:digital envelope routines::unsupported 是一个 OpenSSL 错误，它表示 digital envelope routines 库中的某些功能不被支持。

**Comment by Jarvlis** [comment]
这个只是警告，并不影响运行呀，项目的运行端口号没出来吗，如果有Error的话，能贴一下报错信息吗

**Comment by lbzlb** [comment]
> 这个只是警告，并不影响运行呀，项目的运行端口号没出来吗，如果有Error的话，能贴一下报错信息吗

他一直卡在这里了，一动不动。等了十几分钟

**Comment by Jarvlis** [comment]
这个和版本有关，在package.json里面的启动命令中加一个这个参数，即可：
![image](https://github.com/Jarvlis/bookSystem-frontend/assets/96105888/ad58f522-b24c-475d-90a4-072fc69a4ec8)

**Comment by lbzlb** [comment]
> 这个和版本有关，在package.json里面的启动命令中加一个这个参数，即可： ![image](https://private-user-images.githubusercontent.com/96105888/344707413-ad58f522-b24c-475d-90a4-072fc69a4ec8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4NDM0MDAsIm5iZiI6MTcxOTg0MzEwMCwicGF0aCI6Ii85NjEwNTg4OC8zNDQ3MDc0MTMtYWQ1OGY1MjItYjI0Yy00NzVkLTkwYTQtMDcyZmM2OWE0ZWM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDE0MTE0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjOWZhZTZjODI0YmRlZjY2OWE4ZmQ4NzhmMDUwZWM2ODUxODhhYzhmNzU4NDBmMDJmMmUzMjg4NDBhZTVmMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nZegUFNIHW5YQrjQ_ZFHFNFtEbubeh68ScPNHtWpQL4)
从您那里下载的文件里有，貌似没起作用
<img width="960" alt="image" src="https://github.com/Jarvlis/bookSystem-frontend/assets/105098674/31e07d2e-c076-4982-8f58-be64de8fba91">

**Comment by Jarvlis** [comment]
你用的什么命令启动的，是npm run start:dev吗

**Comment by lbzlb** [comment]
> 你用的什么命令启动的，是npm run start：dev吗

![image](https://github.com/Jarvlis/bookSystem-frontend/assets/105098674/67f6ed49-d99e-42d2-bc41-ff02858b0adc)

**Comment by Jarvlis** [comment]
你的冒号是用的中文冒号，所以启动失败了，npm run start:dev 要使用英文冒号
